Increasing land generation height
mraof/Minestuck pull request #388
Opened 2022-10-15 01:43 UTC by Dweblenod

It will now match the 1.18 and beyond Overworld at y= -64 to 320. Changes have been made to the height at which the entry platform/island generates and to the gates, we will now be able to fit all 7 gates.

Values that have changed:
-16 blocks from top of entry platform to first gate  -> 4 blocks
-48 blocks between gates -> 30 blocks
-64 blocks between the highest gate and the top of the world -> 16 blocks
-top of entry platform generating at y=128 -> y=120

2022-10-20 16:42 UTC, kirderf1 requested changes
Changing hardcoded height values in worldgen features to new hardcoded values doesn't seem like a good solution. How about taking an approach with `Integer.MIN_VALUE` and `Integer.MAX_VALUE`?
On another regard, could you tweak the y gradient for the depth functions in `MSDensityFunctions`?

2022-10-23 08:59 UTC, kirderf1 requested changes
You should probably also tweak placement range and frequencies of underground worldgen features, and potentially also carvers.

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/feature/FloorCogFeature.java
> +		int yMin = Integer.MAX_VALUE, yMax = -64;
```suggestion
		int yMin = level.getMaxBuildHeight(), yMax = level.getMinBuildHeight();
```

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/feature/OasisFeature.java
> +		int yMin = 320, yMax = -64;
```suggestion
		int yMin = level.getMaxBuildHeight(), yMax = level.getMinBuildHeight();
```

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/feature/SmallLibraryFeature.java
> +		int y1 = -64;
```suggestion
		int y1 = level.getMinBuildHeight();
```

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/feature/SmallLibraryFeature.java
> +		int y2 = -64;
```suggestion
		int y2 = level.getMinBuildHeight();
```

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/feature/SurfaceFossilsFeature.java
> +		int yMin = Integer.MAX_VALUE, yMax = -64;
```suggestion
		int yMin = level.getMaxBuildHeight(), yMax = level.getMinBuildHeight();
```

2022-10-23 08:59 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/world/gen/structure/SmallRuinPiece.java
> +		int minY = 320, maxY = -64;
```suggestion
		int minY = level.getMaxBuildHeight(), maxY = level.getMinBuildHeight();
```

2022-10-26 19:39 UTC, kirderf1 approved these changes

2022-10-28 13:13 UTC, Dweblenod commented
It has been mentioned in personal messages, but there is a delay to this because of bugs related to opening worlds in which chunks were loaded before the increase in world height

2022-10-29 14:01 UTC, Dweblenod commented
When viewing all worlds, there is no error or warning message but upon attempting to load old worlds a warning message appears. We will not be fixing it so that old versions can be upgraded at the moment, but will try to make it absolutely clear that pre-1.18 worlds can not be opened without potential crashes or corruption

2022-10-29 14:01 UTC, merged