Shadeblock PR continuation
mraof/Minestuck pull request #430
Opened 2023-03-16 03:42 UTC by Dweblenod

A continuation of #423 which incorporates the new blocks into the rough biome of Shade lands. Includes fixes/tweaks to previous PR. Also adds visual offset to various minestuck vegetation blocks once placed

2023-03-22 16:36 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/block/MSBlocks.java
> +	//TODO bottom of log does not use log texture
I guess this is not solved yet?

2023-03-30 10:59 UTC, kirderf1 requested changes

2023-03-30 21:00 UTC, Dweblenod commented on src/main/java/com/mraof/minestuck/block/plant/StrippableFlammableLogBlock.java
> +	}
That makes it a lot more clean! Didnt realize it was there

2023-03-30 22:08 UTC, Dweblenod commented on src/main/java/com/mraof/minestuck/block/plant/GlowingMushroomVinesBlock.java
> +	}
The implementation of this has issues. if the block above is broken the vine does not drop for whatever reason

2023-04-06 12:37 UTC, merged