Fix: Fake players injuring mobs crashes server
mraof/Minestuck pull request #513
Opened 2023-09-23 23:03 UTC by Dweblenod

Fake players were getting their data from PlayerSavedData checked for underling damage modifier. This fixes that.

Also reorganized the code for legibility,

2023-09-23 23:04 UTC, Dweblenod commented
Unable to test with runServer but it works in singleplayer!

Unable to do test in server due to error below
> Task 'prepareRunServerCompile' not found in root project 'Minestuck'.

2023-09-24 14:19 UTC, kirderf1 requested changes

2023-09-24 14:19 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/event/ServerEventHandler.java
> +				boolean attackerIsRealPlayer = attacker instanceof Player && !(attacker instanceof FakePlayer);
Should use `ServerPlayer` instead of `Player` to match the cast in `PlayerSavedData.getData((ServerPlayer) attacker)`

2023-09-24 14:19 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/event/ServerEventHandler.java
> +				boolean attackerIsRealPlayer = attacker instanceof Player && !(attacker instanceof FakePlayer);
```suggestion
				boolean attackerIsRealPlayer = attacker instanceof ServerPlayer && !(attacker instanceof FakePlayer);
```

2023-09-24 14:19 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/event/ServerEventHandler.java
> +				} else if (injured instanceof ServerPlayer player && attacker instanceof UnderlingEntity)
How about checking `!(injured instanceof FakePlayer)` while at it?

2023-09-24 14:19 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/event/ServerEventHandler.java
> +				} else if (injured instanceof ServerPlayer player && attacker instanceof UnderlingEntity)
```suggestion
				} else if (injured instanceof ServerPlayer player && !(injured instanceof FakePlayer) && attacker instanceof UnderlingEntity)
```

2023-09-24 14:19 UTC, kirderf1 commented on CHANGELOG.md
> +- Fake players no longer crash the game when injuring underlings
```suggestion
- Fix a crash from fake players injuring underlings
```

2023-09-24 16:05 UTC, Dweblenod commented
Due to inability to use runServer, unable to test the librarian patch

2023-09-30 19:17 UTC, kirderf1 approved these changes

2023-10-01 17:54 UTC, merged